# main
close_enough: 0.1
target_dt: 0.04 # this (s) should be slower than or equals to main_iter_rate (Hz)
average_speed: 0.2
cell_size: 0.05
inflation_radius: 0.22
log_odds_thresh: 10 # this should be smaller than log_odds_cap
log_odds_cap: 20
main_iter_rate: 25 

# motion
verbose_motion: true
use_internal_odom: false
tune_filter: true
axle_track: 0.16
wheel_radius: 0.033
weight_odom_v: 0.9
weight_odom_w: 0.8
straight_thresh: 0.05
motion_iter_rate: 50

# weight_odom_v tuning:
# 1.0: 0.025, 0.9: 0.017, 0.8: 0.023, 0.7: 0.033, 0.6: 0.050, 0.5: 0.60, 0.4: 0.095, 0.3: 0.137, 0.2: 0.251, 0.1: 0.545 (0-0.2, 0.2-0 after 4m until 5m)

# weight_odom_w tuning:
# 1.0: 6.03, 0.9: 5.52, 0.8: 5.02, 0.7: 4.69, 0.6: 3.09, 0.5: 2.40, 0.4: 2.26, 0.3: 1.83, 0.2: 1.28, 0.1: 0.64 0.0: 0.01 (0-0.5, 0.5-0 after 1st rot until 2nd compl)
# 1.0: 12.2, 0.9: 11.8, 0.8: 9.19, 0.7: 8.80, 0.6: 8.31, 0.5: 6.34, 0.4: 4.89, 0.3: 3.56, 0.2: 2.61, 0.1: 1.10 0.0: 0.02 (0-1, 1-0 after 4th rot until 5th compl)

# move
enable_move: false
verbose_move: true
Kp_lin: 1.0
Ki_lin: 0.0
Kd_lin: 0.0
max_lin_vel: 0.22 # max is 0.22
max_lin_acc: 0.5
Kp_ang: 1.0
Ki_ang: 0.0
Kd_ang: 0.0
max_ang_vel: 2.84 # max is 2.84
max_ang_acc: 2
move_iter_rate: 25
