# main
close_enough: 0.1
target_dt: 0.04 # this (s) should be slower than or equals to main_iter_rate (Hz)
average_speed: 0.2
cell_size: 0.05
inflation_radius: 0.22
log_odds_thresh: 10 # this should be smaller than log_odds_cap
log_odds_cap: 20
main_iter_rate: 25 

# motion
verbose_motion: true
use_internal_odom: false
tune_filter: true
axle_track: 0.16
wheel_radius: 0.033
weight_odom_v: 0.9  # 1.0: 0.49, 0.9: 0.8, 0.8: 0.83, 0.7: 0.83, 0.6: 0.84, 0.5: 0.865, 0.4: 0.87, 0.3: 0.95, 0.2: 1.04, 0.1: 1.34 (0-0.2, 0.2-0 after 4m until 5m)
weight_odom_w: 0.1 # 0.9: 98, 0.8: 84.5, 0.7: 75, 0.6: 64, 0.5: 54, 0.4: 40, 0.3: 23, 0.2: 21, 0.1: 11, 0.0: 0 (0-0.5, 0.5-0 after 1st rot until 2nd compl)
straight_thresh: 0.05
motion_iter_rate: 50

# move
enable_move: false
verbose_move: true
Kp_lin: 1.0
Ki_lin: 0.0
Kd_lin: 0.0
max_lin_vel: 0.22 # max is 0.22
max_lin_acc: 0.5
Kp_ang: 1.0
Ki_ang: 0.0
Kd_ang: 0.0
max_ang_vel: 2.84 # max is 2.84
max_ang_acc: 2
move_iter_rate: 25
